### ISSUE TITLE
Show when line is reached (xdebug breakpoint)

### ISSUE THREAD

**Issue by eternaleclipse** [cyrus-and/fracker#6]
I suggest adding a flag to show when a certain file:line is reached, ex.
```bash
$ fracker -l 1.php:23
...
Reached line 1.php:23
...
```

Another useful feature would be a flag to print every PHP line executed (similar to `python -m trace 1.py`).

This could be very useful for collecting coverage data and debugging complex branching logic inside a single function (ex. parsers).

If we take this idea further, executing custom PHP code when a breakpoint / function call / return is reached would be amazing.

**Comment by cyrus-and** [comment]
> I suggest adding a flag to show when a certain file:line is reached, ex.

Good idea, I could quite trivially match the regexps provided via the `--paths` and `--exclude-paths` against `PATH:LINE` instead of just `PATH`.

> Another useful feature would be a flag to print every PHP line executed (similar to `python -m trace 1.py`).

AFAIK this cannot be done since I don't have source code information, via Xdebug. I can only hook the called functions.

> If we take this idea further, executing custom PHP code when a breakpoint / function call / return is reached would be amazing.

Eh, it sounds like injecting PHP code, moves a bit away from the original goal of this project... For example, the *listener* application, is just that, and never communicates back to the PHP extension.

**Comment by cyrus-and** [comment]
Example:

```console
$ fracker -p index.php:3
+++ │ Listening on 0.0.0.0:6666
+++ │
001 │ GET localhost/?x=Hello+Fracker!
001 │ »  »  preg_replace("/[^a-z]/i", "", "Hello") /var/www/html/index.php +3
001 │ »  »  system("echo Hello") /var/www/html/index.php +3
001 │ »  »  preg_replace("/[^a-z]/i", "", "Fracker!") /var/www/html/index.php +3
001 │ »  »  system("echo Fracker") /var/www/html/index.php +3
+++ │
+++ │ Shutting down...
```
